### ISSUE TITLE
Improve mode information

### ISSUE THREAD

**Issue by PiotrOsiewicz** [PiotrOsiewicz/Statula#8]
As of today, it's impossible to tell whether we have no mode in given dataset since the message for that is "No mode/more than one mode" - ideally we'd like to remove any ambiguity by changing MODE_PRESENT flag into two: MULTIPLE_MODES and NO_MODE - if they are both set to 0 then that means that we have only one mode and that dataset->mode is valid. Default state for these flags should be (respectively) 0 and 1.

**Comment by rjalfa** [comment]
What do you mean by NO_MODE, as a data set will always contain at least one mode. Is this for handling 0-sized arrays?

**Comment by PiotrOsiewicz** [comment]
Yes, exactly. Sorry for not clearing that up.

**Comment by PiotrOsiewicz** [comment]
Yes, exactly. Sorry for not being clear enough. :smile:
