### ISSUE TITLE
Revisit macro naming

### ISSUE THREAD

**Issue by PiotrOsiewicz** [PiotrOsiewicz/Statula#9]
Currently, there are some macros that might collide if some module of this project was to be taken out of it's scope - that is, SORT is really general name. Solution to that problem would be to add prefix "STATULA_" to these.

**Comment by rjalfa** [comment]
It would be nicer to add the prefix to all the macros for uniformity. Is that ok?

**Comment by PiotrOsiewicz** [comment]
Yeah, that's what I had at the end of my tongue whole time. Anyways, I've merged your changes - for whatever reason git won't recognize your changes as 'yours', but I've went ahead and added you to CONTRIBUTORS.md anyways. I hope it's not a problem. Also, please do commits incrementally - as in, you did two of them: macro naming and mode - however mode did not stick to the naming convention introduced with former patch and that was a pain to deal with. 

Anyways, I did not mean to discourage you. Sorry for inconveniences and thank you for contributing.
Best regards

**Comment by rjalfa** [comment]
I didn't read the CONTRIBUTORS file, so I didn't know I had to add my name somewhere.
Also, I thought that I have made a mistake in MACRO RENAME prefix and was with the view that you won't merge that, so I created a different PR. I will take care of that in the future.
Thanks :-)
